-- AUTO-GENERATED by `ingest init-db`. Build BM25 FTS indexes per domain.
-- Run after a bulk ingest:  duckdb _db/knowledge.duckdb < this-file

INSTALL fts;
LOAD fts;

PRAGMA create_fts_index('compintel.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('devin.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('docker.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('ecs.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('exercise.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('firecracker.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('hci.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('k8s.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('linux.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('market.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('methodology.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
PRAGMA create_fts_index('product.documents', 'source_id', 'content_md', stemmer='porter', stopwords='english', overwrite=1);
