-- AUTO-GENERATED by `ingest init-db`. Build HNSW vector indexes per domain.
-- Run after `ingest embed`:  duckdb _db/knowledge.duckdb < this-file

INSTALL vss;
LOAD vss;
SET hnsw_enable_experimental_persistence = true;

CREATE INDEX IF NOT EXISTS compintel_emb_hnsw ON compintel.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS devin_emb_hnsw ON devin.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS docker_emb_hnsw ON docker.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS ecosystem_emb_hnsw ON ecosystem.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS ecs_emb_hnsw ON ecs.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS exercise_emb_hnsw ON exercise.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS finance_emb_hnsw ON finance.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS firecracker_emb_hnsw ON firecracker.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS governance_emb_hnsw ON governance.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS hci_emb_hnsw ON hci.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS linux_emb_hnsw ON linux.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS market_emb_hnsw ON market.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS methodology_emb_hnsw ON methodology.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS product_emb_hnsw ON product.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS strategy_emb_hnsw ON strategy.embeddings USING HNSW (vector) WITH (metric = 'cosine');
CREATE INDEX IF NOT EXISTS voc_emb_hnsw ON voc.embeddings USING HNSW (vector) WITH (metric = 'cosine');
