- generic [ref=e2]:
  - region
  - generic [ref=e3]:
    - link "Skip to content" [ref=e4] [cursor=pointer]:
      - /url: "#start-of-content"
    - banner [ref=e6]:
      - heading "Navigation Menu" [level=2] [ref=e7]
      - generic [ref=e8]:
        - link "Homepage" [ref=e10] [cursor=pointer]:
          - /url: /
          - img [ref=e11]
        - generic [ref=e13]:
          - navigation "Global" [ref=e16]:
            - list [ref=e17]:
              - listitem [ref=e18]:
                - button "Platform" [ref=e20] [cursor=pointer]:
                  - text: Platform
                  - img [ref=e21]
              - listitem [ref=e23]:
                - button "Solutions" [ref=e25] [cursor=pointer]:
                  - text: Solutions
                  - img [ref=e26]
              - listitem [ref=e28]:
                - button "Resources" [ref=e30] [cursor=pointer]:
                  - text: Resources
                  - img [ref=e31]
              - listitem [ref=e33]:
                - button "Open Source" [ref=e35] [cursor=pointer]:
                  - text: Open Source
                  - img [ref=e36]
              - listitem [ref=e38]:
                - button "Enterprise" [ref=e40] [cursor=pointer]:
                  - text: Enterprise
                  - img [ref=e41]
              - listitem [ref=e43]:
                - link "Pricing" [ref=e44] [cursor=pointer]:
                  - /url: https://github.com/pricing
                  - generic [ref=e45]: Pricing
          - generic [ref=e46]:
            - button "Search or jump to…" [ref=e49] [cursor=pointer]:
              - img [ref=e51]
            - link "Sign in" [ref=e54] [cursor=pointer]:
              - /url: /login?return_to=https%3A%2F%2Fgithub.com%2Fbrendangregg%2Fperf-tools
            - link "Sign up" [ref=e55] [cursor=pointer]:
              - /url: /signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F%3Cuser-name%3E%2F%3Crepo-name%3E&source=header-repo&source_repo=brendangregg%2Fperf-tools
            - button "Appearance settings" [ref=e58] [cursor=pointer]:
              - img
  - main [ref=e62]:
    - generic [ref=e63]:
      - generic [ref=e64]:
        - generic [ref=e66]:
          - img [ref=e67]
          - link "brendangregg" [ref=e70] [cursor=pointer]:
            - /url: /brendangregg
          - generic [ref=e71]: /
          - strong [ref=e72]:
            - link "perf-tools" [ref=e73] [cursor=pointer]:
              - /url: /brendangregg/perf-tools
          - generic [ref=e74]: Public
        - generic [ref=e75]:
          - list:
            - listitem [ref=e76]:
              - link "You must be signed in to change notification settings" [ref=e77] [cursor=pointer]:
                - /url: /login?return_to=%2Fbrendangregg%2Fperf-tools
                - img [ref=e78]
                - text: Notifications
            - listitem [ref=e80]:
              - link "Fork 1.7k" [ref=e81] [cursor=pointer]:
                - /url: /login?return_to=%2Fbrendangregg%2Fperf-tools
                - img [ref=e82]
                - text: Fork
                - generic "1,670" [ref=e84]: 1.7k
            - listitem [ref=e85]:
              - link "You must be signed in to star a repository" [ref=e87] [cursor=pointer]:
                - /url: /login?return_to=%2Fbrendangregg%2Fperf-tools
                - img [ref=e88]
                - text: Star
                - generic "10424 users starred this repository" [ref=e90]: 10.4k
      - navigation "Repository" [ref=e91]:
        - list [ref=e92]:
          - listitem [ref=e93]:
            - link "Code" [ref=e94] [cursor=pointer]:
              - /url: /brendangregg/perf-tools
              - img [ref=e95]
              - generic [ref=e97]: Code
          - listitem [ref=e98]:
            - link "Issues 39" [ref=e99] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/issues
              - img [ref=e100]
              - generic [ref=e103]: Issues
              - generic "39" [ref=e104]
          - listitem [ref=e105]:
            - link "Pull requests 15" [ref=e106] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/pulls
              - img [ref=e107]
              - generic [ref=e109]: Pull requests
              - generic "15" [ref=e110]
          - listitem [ref=e111]:
            - link "Actions" [ref=e112] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/actions
              - img [ref=e113]
              - generic [ref=e115]: Actions
          - listitem [ref=e116]:
            - link "Projects" [ref=e117] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/projects
              - img [ref=e118]
              - generic [ref=e120]: Projects
          - listitem [ref=e121]:
            - link "Wiki" [ref=e122] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/wiki
              - img [ref=e123]
              - generic [ref=e125]: Wiki
          - listitem [ref=e126]:
            - link "Security and quality" [ref=e127] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/security
              - img [ref=e128]
              - generic [ref=e130]: Security and quality
          - listitem [ref=e131]:
            - link "Insights" [ref=e132] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/pulse
              - img [ref=e133]
              - generic [ref=e135]: Insights
    - generic [ref=e148]:
      - heading "brendangregg/perf-tools" [level=1] [ref=e150]
      - generic [ref=e151]:
        - generic [ref=e154]:
          - generic [ref=e155]:
            - generic [ref=e156]:
              - button "master branch" [ref=e158] [cursor=pointer]:
                - generic [ref=e159]:
                  - generic [ref=e161]:
                    - img [ref=e163]
                    - generic [ref=e166]: master
                  - generic:
                    - img
              - generic [ref=e167]:
                - link "Go to Branches page" [ref=e168] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/branches
                  - img [ref=e169]
                - link "Go to Tags page" [ref=e171] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/tags
                  - img [ref=e172]
            - generic [ref=e174]:
              - generic [ref=e178]:
                - img [ref=e180]
                - combobox "Go to file" [ref=e182]
              - button "Code" [ref=e183] [cursor=pointer]:
                - generic [ref=e184]:
                  - generic:
                    - img
                  - generic [ref=e185]: Code
                  - generic:
                    - img
          - generic [ref=e186]:
            - generic [ref=e187]:
              - heading "Folders and files" [level=2] [ref=e188]
              - table "Folders and files" [ref=e189]:
                - rowgroup:
                  - row "Name Last commit message Last commit date":
                    - columnheader "Name"
                    - columnheader "Last commit message":
                      - generic "Last commit message"
                    - columnheader "Last commit date":
                      - generic "Last commit date"
                - rowgroup [ref=e190]:
                  - 'row "Latest commit brendangregg commits by brendangregg Merge pull request #71 from acyberexpert/master Open commit details Commit cb42511 · Jan 14, 20207 years ago History 206 Commits" [ref=e191]':
                    - 'cell "Latest commit brendangregg commits by brendangregg Merge pull request #71 from acyberexpert/master Open commit details Commit cb42511 · Jan 14, 20207 years ago History 206 Commits" [ref=e192]':
                      - generic [ref=e193]:
                        - heading "Latest commit" [level=2] [ref=e194]
                        - generic [ref=e195]:
                          - generic [ref=e197]:
                            - link "brendangregg" [ref=e198] [cursor=pointer]:
                              - /url: /brendangregg
                              - img "brendangregg" [ref=e199]
                            - link "commits by brendangregg" [ref=e200] [cursor=pointer]:
                              - /url: /brendangregg/perf-tools/commits?author=brendangregg
                              - text: brendangregg
                          - generic [ref=e201]:
                            - generic [ref=e203]:
                              - link "Merge pull request" [ref=e204] [cursor=pointer]:
                                - /url: /brendangregg/perf-tools/commit/cb42511b963a8dd2d8fcca400174c8d5d33a1f37
                              - link "#71" [ref=e205] [cursor=pointer]:
                                - /url: https://github.com/brendangregg/perf-tools/pull/71
                              - link "from acyberexpert/master" [ref=e206] [cursor=pointer]:
                                - /url: /brendangregg/perf-tools/commit/cb42511b963a8dd2d8fcca400174c8d5d33a1f37
                            - button "Open commit details" [ref=e207] [cursor=pointer]:
                              - img [ref=e208]
                        - generic [ref=e210]:
                          - generic [ref=e212]:
                            - link "Commit cb42511" [ref=e213] [cursor=pointer]:
                              - /url: /brendangregg/perf-tools/commit/cb42511b963a8dd2d8fcca400174c8d5d33a1f37
                              - text: cb42511
                            - text: ·
                            - generic "Jan 14, 2020, 5:47 PM EST" [ref=e214]: Jan 14, 20207 years ago
                          - generic [ref=e215]:
                            - heading "History" [level=2] [ref=e216]
                            - link "206 Commits" [ref=e217] [cursor=pointer]:
                              - /url: /brendangregg/perf-tools/commits/master/
                              - generic [ref=e218]:
                                - generic:
                                  - img
                                - generic [ref=e219]: 206 Commits
                  - row "bin, (Directory) uprobe for user-level tracing Jun 28, 201511 years ago" [ref=e220]:
                    - cell "bin, (Directory)" [ref=e221]:
                      - generic [ref=e222]:
                        - img [ref=e223]
                        - link "bin, (Directory)" [ref=e228] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/bin
                          - text: bin
                    - cell "uprobe for user-level tracing" [ref=e229]:
                      - link "uprobe for user-level tracing" [ref=e232] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/71086ef90b3a868f86f08e2b9e7ec6b05854d041
                    - cell "Jun 28, 201511 years ago" [ref=e233]:
                      - generic [ref=e234]: Jun 28, 201511 years ago
                  - row "deprecated, (Directory) execsnoop-proc man page Jul 28, 201412 years ago" [ref=e235]:
                    - cell "deprecated, (Directory)" [ref=e236]:
                      - generic [ref=e237]:
                        - img [ref=e238]
                        - link "deprecated, (Directory)" [ref=e243] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/deprecated
                          - text: deprecated
                    - cell "execsnoop-proc man page" [ref=e244]:
                      - link "execsnoop-proc man page" [ref=e247] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/c033ed7dee3188c8f340fd89c0887bcc5488f697
                    - cell "Jul 28, 201412 years ago" [ref=e248]:
                      - generic [ref=e249]: Jul 28, 201412 years ago
                  - 'row "disk, (Directory) bitesize: work with different versions of awk and bash Jun 6, 201511 years ago" [ref=e250]':
                    - cell "disk, (Directory)" [ref=e251]:
                      - generic [ref=e252]:
                        - img [ref=e253]
                        - link "disk, (Directory)" [ref=e258] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/disk
                          - text: disk
                    - 'cell "bitesize: work with different versions of awk and bash" [ref=e259]':
                      - 'link "bitesize: work with different versions of awk and bash" [ref=e262] [cursor=pointer]':
                        - /url: /brendangregg/perf-tools/commit/7431cc024feaf580f525184387ded3856ed7d314
                    - cell "Jun 6, 201511 years ago" [ref=e263]:
                      - generic [ref=e264]: Jun 6, 201511 years ago
                  - row "examples, (Directory) correct argument in example May 17, 20188 years ago" [ref=e265]:
                    - cell "examples, (Directory)" [ref=e266]:
                      - generic [ref=e267]:
                        - img [ref=e268]
                        - link "examples, (Directory)" [ref=e273] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/examples
                          - text: examples
                    - cell "correct argument in example" [ref=e274]:
                      - link "correct argument in example" [ref=e277] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/f7474acc3cf2671106b694d53e058c8547ee97e6
                    - cell "May 17, 20188 years ago" [ref=e278]:
                      - generic [ref=e279]: May 17, 20188 years ago
                  - row "fs, (Directory) cachestat for page cache statistics Jan 1, 201512 years ago" [ref=e280]:
                    - cell "fs, (Directory)" [ref=e281]:
                      - generic [ref=e282]:
                        - img [ref=e283]
                        - link "fs, (Directory)" [ref=e288] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/fs
                          - text: fs
                    - cell "cachestat for page cache statistics" [ref=e289]:
                      - link "cachestat for page cache statistics" [ref=e292] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/41fe778cd3c38b7844ba42cb686e0dedb52b2ff1
                    - cell "Jan 1, 201512 years ago" [ref=e293]:
                      - generic [ref=e294]: Jan 1, 201512 years ago
                  - row "images, (Directory) update URL Apr 17, 201610 years ago" [ref=e295]:
                    - cell "images, (Directory)" [ref=e296]:
                      - generic [ref=e297]:
                        - img [ref=e298]
                        - link "images, (Directory)" [ref=e303] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/images
                          - text: images
                    - cell "update URL" [ref=e304]:
                      - link "update URL" [ref=e307] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/5a511f5f775cfbc0569e6039435361cecd22dd86
                    - cell "Apr 17, 201610 years ago" [ref=e308]:
                      - generic [ref=e309]: Apr 17, 201610 years ago
                  - 'row "kernel, (Directory) Merge pull request #56 from goldshtn/filter-pid Sep 5, 20179 years ago" [ref=e310]':
                    - cell "kernel, (Directory)" [ref=e311]:
                      - generic [ref=e312]:
                        - img [ref=e313]
                        - link "kernel, (Directory)" [ref=e318] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/kernel
                          - text: kernel
                    - 'cell "Merge pull request #56 from goldshtn/filter-pid" [ref=e319]':
                      - generic [ref=e321]:
                        - link "Merge pull request" [ref=e322] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/5fae92a7b01901be4075090d831107c6db88af9c
                        - link "#56" [ref=e323] [cursor=pointer]:
                          - /url: https://github.com/brendangregg/perf-tools/pull/56
                        - link "from goldshtn/filter-pid" [ref=e324] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/5fae92a7b01901be4075090d831107c6db88af9c
                    - cell "Sep 5, 20179 years ago" [ref=e325]:
                      - generic [ref=e326]: Sep 5, 20179 years ago
                  - 'row "man/man8, (Directory) Merge pull request #56 from goldshtn/filter-pid Sep 5, 20179 years ago" [ref=e327]':
                    - cell "man/man8, (Directory)" [ref=e328]:
                      - generic [ref=e329]:
                        - img [ref=e330]
                        - link "man/man8, (Directory)" [ref=e335] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/man/man8
                          - text: man/man8
                    - 'cell "Merge pull request #56 from goldshtn/filter-pid" [ref=e336]':
                      - generic [ref=e338]:
                        - link "Merge pull request" [ref=e339] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/5fae92a7b01901be4075090d831107c6db88af9c
                        - link "#56" [ref=e340] [cursor=pointer]:
                          - /url: https://github.com/brendangregg/perf-tools/pull/56
                        - link "from goldshtn/filter-pid" [ref=e341] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/5fae92a7b01901be4075090d831107c6db88af9c
                    - cell "Sep 5, 20179 years ago" [ref=e342]:
                      - generic [ref=e343]: Sep 5, 20179 years ago
                  - row "misc, (Directory) Added filters Aug 6, 201511 years ago" [ref=e344]:
                    - cell "misc, (Directory)" [ref=e345]:
                      - generic [ref=e346]:
                        - img [ref=e347]
                        - link "misc, (Directory)" [ref=e352] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/misc
                          - text: misc
                    - cell "Added filters" [ref=e353]:
                      - link "Added filters" [ref=e356] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/0eb3456a91e7d49a540162264235912a502b2235
                    - cell "Aug 6, 201511 years ago" [ref=e357]:
                      - generic [ref=e358]: Aug 6, 201511 years ago
                  - row "net, (Directory) improve error path, and minor adjustments. Sep 8, 201412 years ago" [ref=e359]:
                    - cell "net, (Directory)" [ref=e360]:
                      - generic [ref=e361]:
                        - img [ref=e362]
                        - link "net, (Directory)" [ref=e367] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/net
                          - text: net
                    - cell "improve error path, and minor adjustments." [ref=e368]:
                      - link "improve error path, and minor adjustments." [ref=e371] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/83c84e78c9f8edac83884f295baf32022e99f28a
                    - cell "Sep 8, 201412 years ago" [ref=e372]:
                      - generic [ref=e373]: Sep 8, 201412 years ago
                  - 'row "system, (Directory) tpoint: Make -p switch respect all process'' threads Sep 4, 20179 years ago" [ref=e374]':
                    - cell "system, (Directory)" [ref=e375]:
                      - generic [ref=e376]:
                        - img [ref=e377]
                        - link "system, (Directory)" [ref=e382] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/system
                          - text: system
                    - 'cell "tpoint: Make -p switch respect all process'' threads" [ref=e383]':
                      - 'link "tpoint: Make -p switch respect all process'' threads" [ref=e386] [cursor=pointer]':
                        - /url: /brendangregg/perf-tools/commit/7579fea0ddff6ca010be3292518d37004f34b0ec
                    - cell "Sep 4, 20179 years ago" [ref=e387]:
                      - generic [ref=e388]: Sep 4, 20179 years ago
                  - row "tools, (Directory) learned this the hard way Jul 31, 201412 years ago" [ref=e389]:
                    - cell "tools, (Directory)" [ref=e390]:
                      - generic [ref=e391]:
                        - img [ref=e392]
                        - link "tools, (Directory)" [ref=e397] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/tools
                          - text: tools
                    - cell "learned this the hard way" [ref=e398]:
                      - link "learned this the hard way" [ref=e401] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/edf2fd9801de55c28a329e0c40e9dee03005d39d
                    - cell "Jul 31, 201412 years ago" [ref=e402]:
                      - generic [ref=e403]: Jul 31, 201412 years ago
                  - 'row "user, (Directory) uprobe: Make -p switch respect all process'' threads Sep 4, 20179 years ago" [ref=e404]':
                    - cell "user, (Directory)" [ref=e405]:
                      - generic [ref=e406]:
                        - img [ref=e407]
                        - link "user, (Directory)" [ref=e412] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/tree/master/user
                          - text: user
                    - 'cell "uprobe: Make -p switch respect all process'' threads" [ref=e413]':
                      - 'link "uprobe: Make -p switch respect all process'' threads" [ref=e416] [cursor=pointer]':
                        - /url: /brendangregg/perf-tools/commit/b1fceb7239f6d5556ca7ac3168c1a7ab9491733a
                    - cell "Sep 4, 20179 years ago" [ref=e417]:
                      - generic [ref=e418]: Sep 4, 20179 years ago
                  - row "LICENSE, (File) Initial commit Jul 10, 201412 years ago" [ref=e419]:
                    - cell "LICENSE, (File)" [ref=e420]:
                      - generic [ref=e421]:
                        - img [ref=e422]
                        - link "LICENSE, (File)" [ref=e427] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/LICENSE
                          - text: LICENSE
                    - cell "Initial commit" [ref=e428]:
                      - link "Initial commit" [ref=e431] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/a12c0063e89ed1195752617bd43d8e76de23915e
                    - cell "Jul 10, 201412 years ago" [ref=e432]:
                      - generic [ref=e433]: Jul 10, 201412 years ago
                  - row "README.md, (File) correct spelling mistake Sep 1, 20179 years ago" [ref=e434]:
                    - cell "README.md, (File)" [ref=e435]:
                      - generic [ref=e436]:
                        - img [ref=e437]
                        - link "README.md, (File)" [ref=e442] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/README.md
                          - text: README.md
                    - cell "correct spelling mistake" [ref=e443]:
                      - link "correct spelling mistake" [ref=e446] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/f49e2a97e89cfa1b03fe6de3301b24022c9bc8e2
                    - cell "Sep 1, 20179 years ago" [ref=e447]:
                      - generic [ref=e448]: Sep 1, 20179 years ago
                  - row "execsnoop, (File) Fix usage copy&paste from opensnoop Nov 14, 20179 years ago" [ref=e449]:
                    - cell "execsnoop, (File)" [ref=e450]:
                      - generic [ref=e451]:
                        - img [ref=e452]
                        - link "execsnoop, (File)" [ref=e457] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/execsnoop
                          - text: execsnoop
                    - cell "Fix usage copy&paste from opensnoop" [ref=e458]:
                      - link "Fix usage copy&paste from opensnoop" [ref=e461] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/95d12d92545ffc15fae8a2ff36e7cf219dcc2a7d
                    - cell "Nov 14, 20179 years ago" [ref=e462]:
                      - generic [ref=e463]: Nov 14, 20179 years ago
                  - row "iolatency, (File) trap HUP Jul 24, 201412 years ago" [ref=e464]:
                    - cell "iolatency, (File)" [ref=e465]:
                      - generic [ref=e466]:
                        - img [ref=e467]
                        - link "iolatency, (File)" [ref=e472] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/iolatency
                          - text: iolatency
                    - cell "trap HUP" [ref=e473]:
                      - link "trap HUP" [ref=e476] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/033efc2dd4a443cef1d720246aded27dc695ea1b
                    - cell "Jul 24, 201412 years ago" [ref=e477]:
                      - generic [ref=e478]: Jul 24, 201412 years ago
                  - row "iosnoop, (File) more column adjustments Aug 3, 201412 years ago" [ref=e479]:
                    - cell "iosnoop, (File)" [ref=e480]:
                      - generic [ref=e481]:
                        - img [ref=e482]
                        - link "iosnoop, (File)" [ref=e487] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/iosnoop
                          - text: iosnoop
                    - cell "more column adjustments" [ref=e488]:
                      - link "more column adjustments" [ref=e491] [cursor=pointer]:
                        - /url: /brendangregg/perf-tools/commit/64e299e7a1a4a394f08f2cd06f25071cfb29328a
                    - cell "Aug 3, 201412 years ago" [ref=e492]:
                      - generic [ref=e493]: Aug 3, 201412 years ago
                  - 'row "killsnoop, (File) killsnoop: can''t work with mawk Jan 17, 201512 years ago" [ref=e494]':
                    - cell "killsnoop, (File)" [ref=e495]:
                      - generic [ref=e496]:
                        - img [ref=e497]
                        - link "killsnoop, (File)" [ref=e502] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/killsnoop
                          - text: killsnoop
                    - 'cell "killsnoop: can''t work with mawk" [ref=e503]':
                      - 'link "killsnoop: can''t work with mawk" [ref=e506] [cursor=pointer]':
                        - /url: /brendangregg/perf-tools/commit/a52538f82326750118da9a892ba87a79417844b4
                    - cell "Jan 17, 201512 years ago" [ref=e507]:
                      - generic [ref=e508]: Jan 17, 201512 years ago
                  - 'row "opensnoop, (File) Merge pull request #84 from jamagin/fix-81 Jan 14, 20207 years ago" [ref=e509]':
                    - cell "opensnoop, (File)" [ref=e510]:
                      - generic [ref=e511]:
                        - img [ref=e512]
                        - link "opensnoop, (File)" [ref=e517] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/opensnoop
                          - text: opensnoop
                    - 'cell "Merge pull request #84 from jamagin/fix-81" [ref=e518]':
                      - generic [ref=e520]:
                        - link "Merge pull request" [ref=e521] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/a70d715fc3887ee6db7c6a329c0f3ded63b4a4ff
                        - link "#84" [ref=e522] [cursor=pointer]:
                          - /url: https://github.com/brendangregg/perf-tools/pull/84
                        - link "from jamagin/fix-81" [ref=e523] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/commit/a70d715fc3887ee6db7c6a329c0f3ded63b4a4ff
                    - cell "Jan 14, 20207 years ago" [ref=e524]:
                      - generic [ref=e525]: Jan 14, 20207 years ago
                  - 'row "syscount, (File) syscount: Fix for perf list and perf script. Jul 5, 201511 years ago" [ref=e526]':
                    - cell "syscount, (File)" [ref=e527]:
                      - generic [ref=e528]:
                        - img [ref=e529]
                        - link "syscount, (File)" [ref=e534] [cursor=pointer]:
                          - /url: /brendangregg/perf-tools/blob/master/syscount
                          - text: syscount
                    - 'cell "syscount: Fix for perf list and perf script." [ref=e535]':
                      - 'link "syscount: Fix for perf list and perf script." [ref=e538] [cursor=pointer]':
                        - /url: /brendangregg/perf-tools/commit/56edb4e321f54ab583950e3637faa79d4cf74391
                    - cell "Jul 5, 201511 years ago" [ref=e539]:
                      - generic [ref=e540]: Jul 5, 201511 years ago
            - generic [ref=e542]:
              - generic [ref=e543]:
                - heading "Repository files navigation" [level=2] [ref=e544]
                - navigation "Repository files" [ref=e545]:
                  - list [ref=e546]:
                    - listitem [ref=e547]:
                      - link "README" [ref=e548] [cursor=pointer]:
                        - /url: "#"
                        - img [ref=e550]
                        - generic [ref=e552]: README
                    - listitem [ref=e553]:
                      - link "GPL-2.0 license" [ref=e554] [cursor=pointer]:
                        - /url: "#"
                        - img [ref=e556]
                        - generic [ref=e558]: GPL-2.0 license
                - button "Outline" [ref=e559] [cursor=pointer]:
                  - img [ref=e560]
              - article [ref=e563]:
                - generic [ref=e564]:
                  - heading "perf-tools" [level=1] [ref=e565]
                  - 'link "Permalink: perf-tools" [ref=e566] [cursor=pointer]':
                    - /url: "#perf-tools"
                    - img [ref=e567]
                - paragraph [ref=e569]: A miscellaneous collection of in-development and unsupported performance analysis tools for Linux ftrace and perf_events (aka the "perf" command). Both ftrace and perf are core Linux tracing tools, included in the kernel source. Your system probably has ftrace already, and perf is often just a package add (see Prerequisites).
                - paragraph [ref=e570]: "These tools are designed to be easy to install (fewest dependencies), provide advanced performance observability, and be simple to use: do one thing and do it well. This collection was created by Brendan Gregg (author of the DTraceToolkit)."
                - paragraph [ref=e571]: Many of these tools employ workarounds so that functionality is possible on existing Linux kernels. Because of this, many tools have caveats (see man pages), and their implementation should be considered a placeholder until future kernel features, or new tracing subsystems, are added.
                - paragraph [ref=e572]: These are intended for Linux 3.2 and newer kernels. For Linux 2.6.x, see Warnings.
                - generic [ref=e573]:
                  - heading "Presentation" [level=2] [ref=e574]
                  - 'link "Permalink: Presentation" [ref=e575] [cursor=pointer]':
                    - /url: "#presentation"
                    - img [ref=e576]
                - paragraph [ref=e578]: "These tools were introduced in the USENIX LISA 2014 presentation: Linux Performance Analysis: New Tools and Old Secrets"
                - list [ref=e579]:
                  - listitem [ref=e580]:
                    - text: "slides:"
                    - link "http://www.slideshare.net/brendangregg/linux-performance-analysis-new-tools-and-old-secrets" [ref=e581] [cursor=pointer]:
                      - /url: http://www.slideshare.net/brendangregg/linux-performance-analysis-new-tools-and-old-secrets
                  - listitem [ref=e582]:
                    - text: "video:"
                    - link "https://www.usenix.org/conference/lisa14/conference-program/presentation/gregg" [ref=e583] [cursor=pointer]:
                      - /url: https://www.usenix.org/conference/lisa14/conference-program/presentation/gregg
                - generic [ref=e584]:
                  - heading "Contents" [level=2] [ref=e585]
                  - 'link "Permalink: Contents" [ref=e586] [cursor=pointer]':
                    - /url: "#contents"
                    - img [ref=e587]
                - link [ref=e589] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/blob/master/images/perf-tools_2016.png
                  - img [ref=e590]
                - paragraph [ref=e591]: "Using ftrace:"
                - list [ref=e592]:
                  - listitem [ref=e593]:
                    - link "iosnoop" [ref=e594] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/iosnoop
                    - text: ": trace disk I/O with details including latency."
                    - link "Examples" [ref=e595] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/iosnoop_example.txt
                    - text: .
                  - listitem [ref=e596]:
                    - link "iolatency" [ref=e597] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/iolatency
                    - text: ": summarize disk I/O latency as a histogram."
                    - link "Examples" [ref=e598] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/iolatency_example.txt
                    - text: .
                  - listitem [ref=e599]:
                    - link "execsnoop" [ref=e600] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/execsnoop
                    - text: ": trace process exec() with command line argument details."
                    - link "Examples" [ref=e601] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/execsnoop_example.txt
                    - text: .
                  - listitem [ref=e602]:
                    - link "opensnoop" [ref=e603] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/opensnoop
                    - text: ": trace open() syscalls showing filenames."
                    - link "Examples" [ref=e604] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/opensnoop_example.txt
                    - text: .
                  - listitem [ref=e605]:
                    - link "killsnoop" [ref=e606] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/killsnoop
                    - text: ": trace kill() signals showing process and signal details."
                    - link "Examples" [ref=e607] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/killsnoop_example.txt
                    - text: .
                  - listitem [ref=e608]:
                    - text: fs/
                    - link "cachestat" [ref=e609] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/fs/cachestat
                    - text: ": basic cache hit/miss statistics for the Linux page cache."
                    - link "Examples" [ref=e610] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/cachestat_example.txt
                    - text: .
                  - listitem [ref=e611]:
                    - text: net/
                    - link "tcpretrans" [ref=e612] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/net/tcpretrans
                    - text: ": show TCP retransmits, with address and other details."
                    - link "Examples" [ref=e613] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/tcpretrans_example.txt
                    - text: .
                  - listitem [ref=e614]:
                    - text: system/
                    - link "tpoint" [ref=e615] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/system/tpoint
                    - text: ": trace a given tracepoint."
                    - link "Examples" [ref=e616] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/tpoint_example.txt
                    - text: .
                  - listitem [ref=e617]:
                    - text: kernel/
                    - link "funccount" [ref=e618] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/kernel/funccount
                    - text: ": count kernel function calls, matching a string with wildcards."
                    - link "Examples" [ref=e619] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/funccount_example.txt
                    - text: .
                  - listitem [ref=e620]:
                    - text: kernel/
                    - link "functrace" [ref=e621] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/kernel/functrace
                    - text: ": trace kernel function calls, matching a string with wildcards."
                    - link "Examples" [ref=e622] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/functrace_example.txt
                    - text: .
                  - listitem [ref=e623]:
                    - text: kernel/
                    - link "funcslower" [ref=e624] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/kernel/funcslower
                    - text: ": trace kernel functions slower than a threshold."
                    - link "Examples" [ref=e625] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/funcslower_example.txt
                    - text: .
                  - listitem [ref=e626]:
                    - text: kernel/
                    - link "funcgraph" [ref=e627] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/kernel/funcgraph
                    - text: ": trace a graph of kernel function calls, showing children and times."
                    - link "Examples" [ref=e628] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/funcgraph_example.txt
                    - text: .
                  - listitem [ref=e629]:
                    - text: kernel/
                    - link "kprobe" [ref=e630] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/kernel/kprobe
                    - text: ": dynamically trace a kernel function call or its return, with variables."
                    - link "Examples" [ref=e631] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/kprobe_example.txt
                    - text: .
                  - listitem [ref=e632]:
                    - text: user/
                    - link "uprobe" [ref=e633] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/user/uprobe
                    - text: ": dynamically trace a user-level function call or its return, with variables."
                    - link "Examples" [ref=e634] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/uprobe_example.txt
                    - text: .
                  - listitem [ref=e635]:
                    - text: tools/
                    - link "reset-ftrace" [ref=e636] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/tools/reset-ftrace
                    - text: ": reset ftrace state if needed."
                    - link "Examples" [ref=e637] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/reset-ftrace_example.txt
                    - text: .
                - paragraph [ref=e638]: "Using perf_events:"
                - list [ref=e639]:
                  - listitem [ref=e640]:
                    - text: misc/
                    - link "perf-stat-hist" [ref=e641] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/misc/perf-stat-hist
                    - text: ": power-of aggregations for tracepoint variables."
                    - link "Examples" [ref=e642] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/perf-stat-hist_example.txt
                    - text: .
                  - listitem [ref=e643]:
                    - link "syscount" [ref=e644] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/syscount
                    - text: ": count syscalls by syscall or process."
                    - link "Examples" [ref=e645] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/syscount_example.txt
                    - text: .
                  - listitem [ref=e646]:
                    - text: disk/
                    - link "bitesize" [ref=e647] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/disk/bitesize
                    - text: ": histogram summary of disk I/O size."
                    - link "Examples" [ref=e648] [cursor=pointer]:
                      - /url: /brendangregg/perf-tools/blob/master/examples/bitesize_example.txt
                    - text: .
                - paragraph [ref=e649]: "Using eBPF:"
                - list [ref=e650]:
                  - listitem [ref=e651]:
                    - text: As a preview of things to come, see the bcc tracing
                    - link "Tools section" [ref=e652] [cursor=pointer]:
                      - /url: https://github.com/iovisor/bcc/blob/master/README.md#tracing
                    - text: . These use
                    - link "bcc" [ref=e653] [cursor=pointer]:
                      - /url: https://github.com/iovisor/bcc
                    - text: ", a front end for using"
                    - link "eBPF" [ref=e654] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2015-05-15/ebpf-one-small-step.html
                    - text: . bcc+eBPF will allow some of these tools to be rewritten and improved, and additional tools to be created.
                - generic [ref=e655]:
                  - heading "Screenshots" [level=2] [ref=e656]
                  - 'link "Permalink: Screenshots" [ref=e657] [cursor=pointer]':
                    - /url: "#screenshots"
                    - img [ref=e658]
                - paragraph [ref=e660]: "Showing new processes and arguments:"
                - generic [ref=e661]: "# ./execsnoop Tracing exec()s. Ctrl-C to end. PID PPID ARGS 22898 22004 man ls 22905 22898 preconv -e UTF-8 22908 22898 pager -s 22907 22898 nroff -mandoc -rLL=164n -rLT=164n -Tutf8 22906 22898 tbl 22911 22910 locale charmap 22912 22907 groff -mtty-char -Tutf8 -mandoc -rLL=164n -rLT=164n 22913 22912 troff -mtty-char -mandoc -rLL=164n -rLT=164n -Tutf8 22914 22912 grotty"
                - paragraph [ref=e662]: "Measuring block device I/O latency from queue insert to completion:"
                - generic [ref=e663]: "# ./iolatency -Q Tracing block I/O. Output every 1 seconds. Ctrl-C to end. >=(ms) .. <(ms) : I/O |Distribution | 0 -> 1 : 1913 |######################################| 1 -> 2 : 438 |######### | 2 -> 4 : 100 |## | 4 -> 8 : 145 |### | 8 -> 16 : 43 |# | 16 -> 32 : 43 |# | 32 -> 64 : 1 |# | [...]"
                - paragraph [ref=e664]: "Tracing the block:block_rq_insert tracepoint, with kernel stack traces, and only for reads:"
                - generic [ref=e665]: "# ./tpoint -s block:block_rq_insert 'rwbs ~ \"*R*\"' cksum-11908 [000] d... 7269839.919098: block_rq_insert: 202,1 R 0 () 736560 + 136 [cksum] cksum-11908 [000] d... 7269839.919107: => __elv_add_request => blk_flush_plug_list => blk_finish_plug => __do_page_cache_readahead => ondemand_readahead => page_cache_async_readahead => generic_file_read_iter => new_sync_read => vfs_read => SyS_read => system_call_fastpath [...]"
                - paragraph [ref=e666]: "Count kernel function calls beginning with \"bio_\", summarize every second:"
                - generic [ref=e667]: "# ./funccount -i 1 'bio_*' Tracing \"bio_*\"... Ctrl-C to end. FUNC COUNT bio_attempt_back_merge 26 bio_get_nr_vecs 361 bio_alloc 536 bio_alloc_bioset 536 bio_endio 536 bio_free 536 bio_fs_destructor 536 bio_init 536 bio_integrity_enabled 536 bio_put 729 bio_add_page 1004 [...]"
                - paragraph [ref=e668]:
                  - text: There are many more examples in the
                  - link "examples" [ref=e669] [cursor=pointer]:
                    - /url: /brendangregg/perf-tools/blob/master/examples
                  - text: directory. Also see the
                  - link "man pages" [ref=e670] [cursor=pointer]:
                    - /url: /brendangregg/perf-tools/blob/master/man/man8
                  - text: .
                - generic [ref=e671]:
                  - heading "Prerequisites" [level=2] [ref=e672]
                  - 'link "Permalink: Prerequisites" [ref=e673] [cursor=pointer]':
                    - /url: "#prerequisites"
                    - img [ref=e674]
                - paragraph [ref=e676]: The intent is as few as possible. Eg, a Linux 3.2 server without debuginfo. See the tool man page for specifics.
                - generic [ref=e677]:
                  - heading "ftrace" [level=3] [ref=e678]
                  - 'link "Permalink: ftrace" [ref=e679] [cursor=pointer]':
                    - /url: "#ftrace"
                    - img [ref=e680]
                - paragraph [ref=e682]: FTRACE configured in the kernel. You may already have this configured and available in your kernel version, as FTRACE was first added in 2.6.27. This requires CONFIG_FTRACE and other FTRACE options depending on the tool. Some tools (eg, funccount) require CONFIG_FUNCTION_PROFILER.
                - generic [ref=e683]:
                  - heading "perf_events" [level=3] [ref=e684]
                  - 'link "Permalink: perf_events" [ref=e685] [cursor=pointer]':
                    - /url: "#perf_events"
                    - img [ref=e686]
                - paragraph [ref=e688]:
                  - text: Requires the "perf" command to be installed. This is in the linux-tools-common package. After installing that, perf may tell you to install an additional linux-tools package (linux-tools-
                  - emphasis [ref=e689]: kernel_version
                  - text: ). perf can also be built under tools/perf in the kernel source. See
                  - link "perf_events Prerequisites" [ref=e690] [cursor=pointer]:
                    - /url: http://www.brendangregg.com/perf.html#Prerequisites
                  - text: for more details about getting perf_events to work fully.
                - generic [ref=e691]:
                  - heading "debugfs" [level=3] [ref=e692]
                  - 'link "Permalink: debugfs" [ref=e693] [cursor=pointer]':
                    - /url: "#debugfs"
                    - img [ref=e694]
                - paragraph [ref=e696]: "Requires a kernel with CONFIG_DEBUG_FS option enabled. As with FTRACE, this may already be enabled (debugfs was added in 2.6.10-rc3). The debugfs also needs to be mounted:"
                - generic [ref=e697]:
                  - code [ref=e699]: "# mount -t debugfs none /sys/kernel/debug"
                  - button "Copy" [ref=e701] [cursor=pointer]:
                    - img [ref=e702]
                - generic [ref=e705]:
                  - heading "awk" [level=3] [ref=e706]
                  - 'link "Permalink: awk" [ref=e707] [cursor=pointer]':
                    - /url: "#awk"
                    - img [ref=e708]
                - paragraph [ref=e710]: "Many of there scripts use awk, and will try to use either mawk or gawk depending on the desired behavior: mawk for buffered output (because of its speed), and gawk for synchronous output (as fflush() works, allowing more efficient grouping of writes)."
                - generic [ref=e711]:
                  - heading "Install" [level=2] [ref=e712]
                  - 'link "Permalink: Install" [ref=e713] [cursor=pointer]':
                    - /url: "#install"
                    - img [ref=e714]
                - paragraph [ref=e716]: "These are just scripts. Either grab everything:"
                - generic [ref=e717]:
                  - code [ref=e719]: git clone --depth 1 https://github.com/brendangregg/perf-tools
                  - button "Copy" [ref=e721] [cursor=pointer]:
                    - img [ref=e722]
                - paragraph [ref=e725]: "Or use the raw links on github to download individual scripts. Eg:"
                - generic [ref=e726]:
                  - code [ref=e728]: wget https://raw.githubusercontent.com/brendangregg/perf-tools/master/iosnoop
                  - button "Copy" [ref=e730] [cursor=pointer]:
                    - img [ref=e731]
                - paragraph [ref=e734]: This preserves tabs (which copy-n-paste can mess up).
                - generic [ref=e735]:
                  - heading "Warnings" [level=2] [ref=e736]
                  - 'link "Permalink: Warnings" [ref=e737] [cursor=pointer]':
                    - /url: "#warnings"
                    - img [ref=e738]
                - paragraph [ref=e740]: Ftrace was first added to Linux 2.6.27, and perf_events to Linux 2.6.31. These early versions had kernel bugs, and lockups and panics have been reported on 2.6.32 series kernels. This includes CentOS 6.x. If you must analyze older kernels, these tools may only be useful in a fault-tolerant environment, such as a lab with simulated issues. These tools have been primarily developed on Linux 3.2 and later kernels.
                - paragraph [ref=e741]: Depending on the tool, there may also be overhead incurred. See the next section.
                - generic [ref=e742]:
                  - heading "Internals and Overhead" [level=2] [ref=e743]
                  - 'link "Permalink: Internals and Overhead" [ref=e744] [cursor=pointer]':
                    - /url: "#internals-and-overhead"
                    - img [ref=e745]
                - paragraph [ref=e747]: perf_events is evolving. This collection began development circa Linux 3.16, with Linux 3.2 servers as the main target, at a time when perf_events lacks certain programmatic capabilities (eg, custom in-kernel aggregations). It's possible these will be added in a forthcoming kernel release. Until then, many of these tools employ workarounds, tricks, and hacks in order to work. Some of these tools pass event data to user space for post-processing, which costs much higher overhead than in-kernel aggregations. The overhead of each tool is described in its man page.
                - paragraph [ref=e748]:
                  - strong [ref=e749]: WARNING
                  - text: ": In"
                  - emphasis [ref=e750]: extreme
                  - text: cases, your target application may run 5x slower when using these tools. Depending on the tool and kernel version, there may also be the risk of kernel panics. Read the program header for warnings, and test before use.
                - paragraph [ref=e751]: If the overhead is a problem, these tools can be improved. If a tool doesn't already, it could be rewritten in C to use perf_events_open() and mmap() for the trace buffer. It could also implement frequency counts in C, and operate on mmap() directly, rather than using awk/Perl/Python. Additional improvements are possible for ftrace-based tools, such as use of snapshots and per-instance buffers.
                - paragraph [ref=e752]: Some of these tools are intended as short-term workarounds until more kernel capabilities exist, at which point they can be substantially rewritten. Older versions of these tools will be kept in this repository, for older kernel versions.
                - paragraph [ref=e753]: As my main target is a fleet of Linux 3.2 servers that do not have debuginfo, these tools try not to require it. At times, this makes the tool more brittle than it needs to be, as I'm employing workarounds (that may be kernel version and platform specific) instead of using debuginfo information (which can be generic). See the man page for detailed prerequisites for each tool.
                - paragraph [ref=e754]: I've tried to use perf_events ("perf") where possible, since that interface has been developed for multi-user use. For various reasons I've often needed to use ftrace instead. ftrace is surprisingly powerful (thanks Steven Rostedt!), and not all of its features are exposed via perf, or in common usage. This tool collection is in some ways a demonstration of hidden Linux features using ftrace.
                - paragraph [ref=e755]: Since things are changing, it's very possible you may find some tools don't work on your Linux kernel version. Some expertise and assembly will be required to fix them.
                - generic [ref=e756]:
                  - heading "Links" [level=2] [ref=e757]
                  - 'link "Permalink: Links" [ref=e758] [cursor=pointer]':
                    - /url: "#links"
                    - img [ref=e759]
                - paragraph [ref=e761]: "A case study and summary:"
                - list [ref=e762]:
                  - listitem [ref=e763]:
                    - text: "13 Aug 2014:"
                    - link "http://lwn.net/Articles/608497" [ref=e764] [cursor=pointer]:
                      - /url: http://lwn.net/Articles/608497
                    - text: "Ftrace: The hidden light switch"
                - paragraph [ref=e765]: "Related articles:"
                - list [ref=e766]:
                  - listitem [ref=e767]:
                    - text: "28 Jun 2015:"
                    - link "http://www.brendangregg.com/blog/2015-06-28/linux-ftrace-uprobe.html" [ref=e768] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2015-06-28/linux-ftrace-uprobe.html
                  - listitem [ref=e769]:
                    - text: "31 Dec 2014:"
                    - link "http://www.brendangregg.com/blog/2014-12-31/linux-page-cache-hit-ratio.html" [ref=e770] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-12-31/linux-page-cache-hit-ratio.html
                  - listitem [ref=e771]:
                    - text: "06 Sep 2014:"
                    - link "http://www.brendangregg.com/blog/2014-09-06/linux-ftrace-tcp-retransmit-tracing.html" [ref=e772] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-09-06/linux-ftrace-tcp-retransmit-tracing.html
                  - listitem [ref=e773]:
                    - text: "28 Jul 2014:"
                    - link "http://www.brendangregg.com/blog/2014-07-28/execsnoop-for-linux.html" [ref=e774] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-07-28/execsnoop-for-linux.html
                  - listitem [ref=e775]:
                    - text: "25 Jul 2014:"
                    - link "http://www.brendangregg.com/blog/2014-07-25/opensnoop-for-linux.html" [ref=e776] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-07-25/opensnoop-for-linux.html
                  - listitem [ref=e777]:
                    - text: "23 Jul 2014:"
                    - link "http://www.brendangregg.com/blog/2014-07-23/linux-iosnoop-latency-heat-maps.html" [ref=e778] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-07-23/linux-iosnoop-latency-heat-maps.html
                  - listitem [ref=e779]:
                    - text: "16 Jul 2014:"
                    - link "http://www.brendangregg.com/blog/2014-07-16/iosnoop-for-linux.html" [ref=e780] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-07-16/iosnoop-for-linux.html
                  - listitem [ref=e781]:
                    - text: "10 Jul 2014:"
                    - link "http://www.brendangregg.com/blog/2014-07-10/perf-hacktogram.html" [ref=e782] [cursor=pointer]:
                      - /url: http://www.brendangregg.com/blog/2014-07-10/perf-hacktogram.html
        - generic [ref=e786]:
          - generic [ref=e789]:
            - heading "About" [level=2] [ref=e790]
            - paragraph [ref=e791]: Performance analysis tools based on Linux perf_events (aka perf) and ftrace
            - heading "Resources" [level=3] [ref=e792]
            - link "Readme" [ref=e794] [cursor=pointer]:
              - /url: "#readme-ov-file"
              - img [ref=e795]
              - text: Readme
            - heading "License" [level=3] [ref=e797]
            - link "GPL-2.0 license" [ref=e799] [cursor=pointer]:
              - /url: "#GPL-2.0-1-ov-file"
              - img [ref=e800]
              - text: GPL-2.0 license
            - link "Activity" [ref=e803] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/activity
              - img [ref=e804]
              - text: Activity
            - heading "Stars" [level=3] [ref=e806]
            - link "10.4k stars" [ref=e808] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/stargazers
              - img [ref=e809]
              - strong [ref=e811]: 10.4k
              - text: stars
            - heading "Watchers" [level=3] [ref=e812]
            - link "598 watching" [ref=e814] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/watchers
              - img [ref=e815]
              - strong [ref=e817]: "598"
              - text: watching
            - heading "Forks" [level=3] [ref=e818]
            - link "1.7k forks" [ref=e820] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/forks
              - img [ref=e821]
              - strong [ref=e823]: 1.7k
              - text: forks
            - link "Report repository" [ref=e825] [cursor=pointer]:
              - /url: /contact/report-content?content_url=https%3A%2F%2Fgithub.com%2Fbrendangregg%2Fperf-tools&report=brendangregg+%28user%29
          - generic [ref=e827]:
            - heading "Releases 1" [level=2] [ref=e828]:
              - link "Releases 1" [ref=e829] [cursor=pointer]:
                - /url: /brendangregg/perf-tools/releases
                - text: Releases
                - generic "1" [ref=e830]
            - link "First Tagged Release (17-Aug-2017) Latest Aug 17, 2017on Aug 17, 2017" [ref=e831] [cursor=pointer]:
              - /url: /brendangregg/perf-tools/releases/tag/v1.0
              - img [ref=e832]
              - generic [ref=e834]:
                - generic [ref=e835]:
                  - generic [ref=e836]: First Tagged Release (17-Aug-2017)
                  - 'generic "Label: Latest" [ref=e837]': Latest
                - generic [ref=e838]: Aug 17, 2017on Aug 17, 2017
          - generic [ref=e840]:
            - heading "Packages" [level=2] [ref=e841]:
              - link "Packages" [ref=e842] [cursor=pointer]:
                - /url: /users/brendangregg/packages?repo_name=perf-tools
            - generic [ref=e843]: No packages published
          - generic [ref=e845]:
            - heading "Contributors 14" [level=2] [ref=e846]:
              - link "Contributors 14" [ref=e847] [cursor=pointer]:
                - /url: /brendangregg/perf-tools/graphs/contributors
                - text: Contributors
                - generic "14" [ref=e848]
            - list [ref=e849]:
              - listitem [ref=e850]:
                - link "@brendangregg" [ref=e851] [cursor=pointer]:
                  - /url: https://github.com/brendangregg
                  - img "@brendangregg" [ref=e852]
              - listitem [ref=e853]:
                - link "@goldshtn" [ref=e854] [cursor=pointer]:
                  - /url: https://github.com/goldshtn
                  - img "@goldshtn" [ref=e855]
              - listitem [ref=e856]:
                - link "@yangoliver" [ref=e857] [cursor=pointer]:
                  - /url: https://github.com/yangoliver
                  - img "@yangoliver" [ref=e858]
              - listitem [ref=e859]:
                - link "@scotte" [ref=e860] [cursor=pointer]:
                  - /url: https://github.com/scotte
                  - img "@scotte" [ref=e861]
              - listitem [ref=e862]:
                - link "@EdwardBetts" [ref=e863] [cursor=pointer]:
                  - /url: https://github.com/EdwardBetts
                  - img "@EdwardBetts" [ref=e864]
              - listitem [ref=e865]:
                - link "@g2p" [ref=e866] [cursor=pointer]:
                  - /url: https://github.com/g2p
                  - img "@g2p" [ref=e867]
              - listitem [ref=e868]:
                - link "@ronin13" [ref=e869] [cursor=pointer]:
                  - /url: https://github.com/ronin13
                  - img "@ronin13" [ref=e870]
              - listitem [ref=e871]:
                - link "@bastianbeischer" [ref=e872] [cursor=pointer]:
                  - /url: https://github.com/bastianbeischer
                  - img "@bastianbeischer" [ref=e873]
              - listitem [ref=e874]:
                - link "@chandranshu12" [ref=e875] [cursor=pointer]:
                  - /url: https://github.com/chandranshu12
                  - img "@chandranshu12" [ref=e876]
              - listitem [ref=e877]:
                - link "@pyKun" [ref=e878] [cursor=pointer]:
                  - /url: https://github.com/pyKun
                  - img "@pyKun" [ref=e879]
              - listitem [ref=e880]:
                - link "@lwindolf" [ref=e881] [cursor=pointer]:
                  - /url: https://github.com/lwindolf
                  - img "@lwindolf" [ref=e882]
              - listitem [ref=e883]:
                - link "@csfrancis" [ref=e884] [cursor=pointer]:
                  - /url: https://github.com/csfrancis
                  - img "@csfrancis" [ref=e885]
              - listitem [ref=e886]:
                - link "@acyberexpert" [ref=e887] [cursor=pointer]:
                  - /url: https://github.com/acyberexpert
                  - img "@acyberexpert" [ref=e888]
              - listitem [ref=e889]:
                - link "@DiegoPomares" [ref=e890] [cursor=pointer]:
                  - /url: https://github.com/DiegoPomares
                  - img "@DiegoPomares" [ref=e891]
          - generic [ref=e893]:
            - heading "Languages" [level=2] [ref=e894]
            - list [ref=e900]:
              - listitem [ref=e901]:
                - link "Shell 88.3%" [ref=e902] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/search?l=shell
                  - img [ref=e903]
                  - generic [ref=e905]: Shell
                  - generic [ref=e906]: 88.3%
              - listitem [ref=e907]:
                - link "Perl 9.8%" [ref=e908] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/search?l=perl
                  - img [ref=e909]
                  - generic [ref=e911]: Perl
                  - generic [ref=e912]: 9.8%
              - listitem [ref=e913]:
                - link "Roff 1.9%" [ref=e914] [cursor=pointer]:
                  - /url: /brendangregg/perf-tools/search?l=roff
                  - img [ref=e915]
                  - generic [ref=e917]: Roff
                  - generic [ref=e918]: 1.9%
  - contentinfo [ref=e920]:
    - heading "Footer" [level=2] [ref=e921]
    - generic [ref=e922]:
      - generic [ref=e923]:
        - link "GitHub Homepage" [ref=e924] [cursor=pointer]:
          - /url: https://github.com
          - img [ref=e925]
        - generic [ref=e927]: © 2026 GitHub, Inc.
      - navigation "Footer" [ref=e928]:
        - heading "Footer navigation" [level=3] [ref=e929]
        - list "Footer navigation" [ref=e930]:
          - listitem [ref=e931]:
            - link "Terms" [ref=e932] [cursor=pointer]:
              - /url: https://docs.github.com/site-policy/github-terms/github-terms-of-service
          - listitem [ref=e933]:
            - link "Privacy" [ref=e934] [cursor=pointer]:
              - /url: https://docs.github.com/site-policy/privacy-policies/github-privacy-statement
          - listitem [ref=e935]:
            - link "Security" [ref=e936] [cursor=pointer]:
              - /url: https://github.com/security
          - listitem [ref=e937]:
            - link "Status" [ref=e938] [cursor=pointer]:
              - /url: https://www.githubstatus.com/
          - listitem [ref=e939]:
            - link "Community" [ref=e940] [cursor=pointer]:
              - /url: https://github.community/
          - listitem [ref=e941]:
            - link "Docs" [ref=e942] [cursor=pointer]:
              - /url: https://docs.github.com/
          - listitem [ref=e943]:
            - link "Contact" [ref=e944] [cursor=pointer]:
              - /url: https://support.github.com?tags=dotcom-footer
          - listitem [ref=e945]:
            - button "Manage cookies" [ref=e947] [cursor=pointer]
          - listitem [ref=e948]:
            - button "Do not share my personal information" [ref=e950] [cursor=pointer]