- generic [active] [ref=e1]:
  - generic [ref=e3]:
    - heading "Performance Analysis Methodology" [level=1] [ref=e4]
    - paragraph [ref=e5]: A performance analysis methodology is a procedure that you can follow to analyze system or application performance. These generally provide a starting point and then guidance to root cause, or causes. Different methodologies are suited for solving different classes of issues, and you may try more than one before accomplishing your goal. Analysis without a methodology can become a fishing expedition, where metrics are examined ad hoc, until the issue is found – if it is at all.
    - paragraph [ref=e6]:
      - text: "Methodologies can help with another difficult issue: when to give up. At any complex environment, spending too much time analyzing one performance problem takes time away from other problems and other possible wins. Performance engineers can spend six months working a single issue without success, when it would be better to try for a week and then turn their attention elsewhere. My recommendation is to try several methodologies on a given issue or theory before moving on, for example:"
      - generic [ref=e7]:
        - text: 1)
        - link "Problem Statement Method" [ref=e8] [cursor=pointer]:
          - /url: "#ProblemStatementMethod"
        - text: ", 2)"
        - link "Workload Characterization Method" [ref=e9] [cursor=pointer]:
          - /url: "#WorkloadCharacterizationMethod"
        - text: ", 3)"
        - link "USE Method" [ref=e10] [cursor=pointer]:
          - /url: usemethod.html
        - text: ", 4)"
        - link "CPU Profile Method" [ref=e11] [cursor=pointer]:
          - /url: "#CPUProfileMethod"
        - text: ", 5)"
        - link "Off-CPU Analysis" [ref=e12] [cursor=pointer]:
          - /url: offcpuanalysis.html
        - text: ", 6)"
        - link "Time Division Method" [ref=e13] [cursor=pointer]:
          - /url: "#TimeDivisionMethod"
        - text: .
    - paragraph [ref=e14]: "Methodologies documented in more detail on this site (beyond this summary page) are:"
    - list [ref=e15]:
      - listitem [ref=e16]:
        - link "The USE Method" [ref=e17] [cursor=pointer]:
          - /url: usemethod.html
        - text: ": for finding resource bottlenecks"
      - listitem [ref=e18]:
        - link "The TSA Method" [ref=e19] [cursor=pointer]:
          - /url: tsamethod.html
        - text: ": for analyzing application time"
      - listitem [ref=e20]:
        - link "Off-CPU Analysis" [ref=e21] [cursor=pointer]:
          - /url: offcpuanalysis.html
        - text: ": for analyzing any type of thread wait latency"
      - listitem [ref=e22]:
        - link "Active Benchmarking" [ref=e23] [cursor=pointer]:
          - /url: activebenchmarking.html
        - text: ": for accurate and successful benchmarking"
    - paragraph [ref=e24]: The following summarizes methodologies I've either created or encountered. You can print these all out as a cheetsheet/reminder.
    - heading "Summaries" [level=2] [ref=e25]
    - paragraph [ref=e26]:
      - text: "I first summarized and named various performance methodologies (mostly developed by me) for my USENIX LISA 2012 talk: Performance Analysis Methodology ("
      - link "PDF" [ref=e27] [cursor=pointer]:
        - /url: http://www.brendangregg.com/Slides/LISA2012_methodologies.pdf
      - text: ","
      - link "slideshare" [ref=e28] [cursor=pointer]:
        - /url: http://www.slideshare.net/brendangregg/lisa12-methodologies
      - text: ","
      - link "youtube" [ref=e29] [cursor=pointer]:
        - /url: http://www.youtube.com/watch?v=abLan0aXJkw
      - text: ","
      - link "USENIX" [ref=e30] [cursor=pointer]:
        - /url: https://www.usenix.org/conference/lisa12/performance-analysis-methodology
      - text: ), then later documented them in my
      - link "Systems Performance" [ref=e31] [cursor=pointer]:
        - /url: systems-performance-2nd-edition-book.html
      - text: book, and the ACMQ article
      - link "Thinking Methodically about Performance" [ref=e32] [cursor=pointer]:
        - /url: http://queue.acm.org/detail.cfm?id=2413037
      - text: ", which was also published in Communications of the ACM, Feb 2013. More detailed references are at the end of this page."
    - paragraph [ref=e33]: The following is my most up to date summary list, with methodologies enumerated. These begin with anti-methods, which are included for comparison, and not to follow.
    - heading "Anti-Methodologies" [level=2] [ref=e34]
    - heading "Blame-Someone-Else Anti-Method" [level=3] [ref=e35]
    - list [ref=e36]:
      - list [ref=e37]:
        - listitem [ref=e38]: Find a system or environment component you are not responsible for
        - listitem [ref=e39]: Hypothesize that the issue is with that component
        - listitem [ref=e40]: Redirect the issue to the responsible team
        - listitem [ref=e41]: When proven wrong, go to 1
    - heading "Streetlight Anti-Method" [level=3] [ref=e42]
    - list [ref=e43]:
      - list [ref=e44]:
        - listitem [ref=e45]: "Pick observability tools that are:"
        - list [ref=e46]:
          - listitem [ref=e47]: familiar
          - listitem [ref=e48]: found on the Internet
          - listitem [ref=e49]: found at random
        - listitem [ref=e50]: Run tools
        - listitem [ref=e51]: Look for obvious issues
    - heading "Drunk Man Anti-Method" [level=3] [ref=e52]
    - list [ref=e53]:
      - list [ref=e54]:
        - listitem [ref=e55]: Change things at random until the problem goes away
    - heading "Random Change Anti-Method" [level=3] [ref=e56]
    - list [ref=e57]:
      - list [ref=e58]:
        - listitem [ref=e59]: Measure a performance baseline
        - listitem [ref=e60]: Pick a random attribute to change (eg, a tunable)
        - listitem [ref=e61]: Change it in one direction
        - listitem [ref=e62]: Measure performance
        - listitem [ref=e63]: Change it in the other direction
        - listitem [ref=e64]: Measure performance
        - listitem [ref=e65]: Were the step 4 or 6 results better than the baseline? If so, keep the change; of not, revert
        - listitem [ref=e66]: Goto step 1
    - heading "Passive Benchmarking Anti-Method" [level=3] [ref=e67]
    - list [ref=e68]:
      - list [ref=e69]:
        - listitem [ref=e70]: Pick a benchmark tool
        - listitem [ref=e71]: Run it with a variety of options
        - listitem [ref=e72]: Make a slide deck of the results
        - listitem [ref=e73]: Hand the slides to management
    - heading "Traffic Light Anti-Method" [level=3] [ref=e74]
    - list [ref=e75]:
      - list [ref=e76]:
        - listitem [ref=e77]: Open dashboard
        - listitem [ref=e78]: All green? Assume everything is good.
        - listitem [ref=e79]: Something red? Assume that's a problem.
    - heading "Methodologies" [level=2] [ref=e80]
    - heading "Ad Hoc Checklist Method" [level=3] [ref=e81]
    - list [ref=e82]:
      - list [ref=e83]:
        - listitem [ref=e84]: ..N. Run A, if B, do C
    - heading "Problem Statement Method" [level=3] [ref=e85]
    - list [ref=e86]:
      - list [ref=e87]:
        - listitem [ref=e88]: What makes you think there is a performance problem?
        - listitem [ref=e89]: Has this system ever performed well?
        - listitem [ref=e90]: What has changed recently? (Software? Hardware? Load?)
        - listitem [ref=e91]: Can the performance degradation be expressed in terms of latency or run time?
        - listitem [ref=e92]: Does the problem affect other people or applications (or is it just you)?
        - listitem [ref=e93]: What is the environment? What software and hardware is used? Versions? Configuration?
    - heading "RTFM Method" [level=3] [ref=e94]
    - list [ref=e95]:
      - paragraph [ref=e96]: "(Read The Fine Manual) How to research performance tools and metrics:"
      - list [ref=e97]:
        - listitem [ref=e98]: Man pages
        - listitem [ref=e99]: Books
        - listitem [ref=e100]: Web search
        - listitem [ref=e101]: Co-workers
        - listitem [ref=e102]: Prior talk slides/video
        - listitem [ref=e103]: Support services
        - listitem [ref=e104]: Source code
        - listitem [ref=e105]: Experimentation
        - listitem [ref=e106]: Social Media
    - heading "Scientific Method" [level=3] [ref=e107]
    - list [ref=e108]:
      - list [ref=e109]:
        - listitem [ref=e110]: Question
        - listitem [ref=e111]: Hypothesis
        - listitem [ref=e112]: Prediction
        - listitem [ref=e113]: Test
        - listitem [ref=e114]: Analysis
    - heading "OODA Loop" [level=3] [ref=e115]
    - list [ref=e116]:
      - list [ref=e117]:
        - listitem [ref=e118]: Observe
        - listitem [ref=e119]: Orient
        - listitem [ref=e120]: Decide
        - listitem [ref=e121]: Act
    - heading "Workload Characterization Method" [level=3] [ref=e122]
    - list [ref=e123]:
      - list [ref=e124]:
        - listitem [ref=e125]: Who is causing the load? (PID, UID, IP addr, customer ID, geographic region, ...)
        - listitem [ref=e126]: Why is the load called? (code path, stack trace, flame graph)
        - listitem [ref=e127]: What is the load? (IOPS, throughput, type, url)
        - listitem [ref=e128]: How is the load changing over time? (time series line graph)
    - heading "Drill-Down Analysis Method" [level=3] [ref=e129]
    - list [ref=e130]:
      - list [ref=e131]:
        - listitem [ref=e132]: Start at highest level
        - listitem [ref=e133]: Examine next-level details
        - listitem [ref=e134]: Pick most interesting breakdown
        - listitem [ref=e135]: If problem unsolved, go to 2
    - heading "Process of Elimination" [level=3] [ref=e136]
    - list [ref=e137]:
      - list [ref=e138]:
        - listitem [ref=e139]: Divide the target into components
        - listitem [ref=e140]: "Choose a test which:"
        - list [ref=e141]:
          - listitem [ref=e142]: Can exonerate many untested components (ideally, half of those remaining)
          - listitem [ref=e143]: Is quick to perform
        - listitem [ref=e144]: Perform test
        - listitem [ref=e145]: Were the tested components exonerated?
        - list [ref=e146]:
          - listitem [ref=e147]: "Yes: go to 2"
          - listitem [ref=e148]: "No: problem found?"
          - list [ref=e149]:
            - listitem [ref=e150]: "Yes: done"
            - listitem [ref=e151]: "No: how many components were tested?"
            - list [ref=e152]:
              - listitem [ref=e153]: "one: target = tested component; go to 1"
              - listitem [ref=e154]: "multiple: go to 2"
          - listitem [ref=e155]: "Not sure: consider components untested; go to 2 and choose a different test"
    - heading "Time Division Method" [level=3] [ref=e156]
    - list [ref=e157]:
      - list [ref=e158]:
        - listitem [ref=e159]: Measure operation time (or latency)
        - listitem [ref=e160]: Divide time into logical synchronous components
        - listitem [ref=e161]: Continue division until latency origin is identified
        - listitem [ref=e162]: "Quantify: estimate speedup if problem fixed"
      - paragraph [ref=e163]: (I previously called this the "Latency Analysis Method")
    - heading "5 Whys Performance Method" [level=3] [ref=e164]
    - list [ref=e165]:
      - list [ref=e166]:
        - listitem [ref=e167]: Given delivered performance, ask, "why?", then answer this question
        - listitem [ref=e168]: ..5 Given previous answer, ask, "why?", then answer this question
    - heading "By-Layer Method" [level=3] [ref=e169]
    - list [ref=e170]:
      - paragraph [ref=e171]: "Measure latency in detail (eg, as a histogram) from:"
      - list [ref=e172]:
        - listitem [ref=e173]: Dynamic languages
        - listitem [ref=e174]: Executable
        - listitem [ref=e175]: Libraries
        - listitem [ref=e176]: Syscalls
        - listitem [ref=e177]: "Kernel: FS, network"
        - listitem [ref=e178]: Device drivers
      - paragraph [ref=e179]: Investigate the lowest layer that latency is introduced
    - heading "Tools Method" [level=3] [ref=e180]
    - list [ref=e181]:
      - list [ref=e182]:
        - listitem [ref=e183]: List available performance tools (optionally add more)
        - listitem [ref=e184]: For each tool, list its useful metrics
        - listitem [ref=e185]: For each metric, list possible interpretation
        - listitem [ref=e186]: Run selected tools and interpret selected metrics.
    - heading "USE Method" [level=3] [ref=e187]
    - list [ref=e188]:
      - paragraph [ref=e189]: "For every resource, check:"
      - list [ref=e190]:
        - listitem [ref=e191]: Utilization
        - listitem [ref=e192]: Saturation
        - listitem [ref=e193]: Errors
    - heading "RED Method" [level=3] [ref=e194]
    - list [ref=e195]:
      - paragraph [ref=e196]: "For every service or microservice, check:"
      - list [ref=e197]:
        - listitem [ref=e198]: Request rate
        - listitem [ref=e199]: Errors
        - listitem [ref=e200]: Duration
    - heading "CPU Profile Method" [level=3] [ref=e201]
    - list [ref=e202]:
      - list [ref=e203]:
        - listitem [ref=e204]:
          - text: Generate a CPU profile (ideally a
          - link "CPU flame graph" [ref=e205] [cursor=pointer]:
            - /url: Flamegraphs/cpuflamegraphs.html
          - text: )
        - listitem [ref=e206]: Understand all software in profile > 1%
    - heading "Off-CPU Analysis" [level=3] [ref=e207]
    - list [ref=e208]:
      - list [ref=e209]:
        - listitem [ref=e210]: Profile per-thread off-CPU time with stack traces
        - listitem [ref=e211]: Coalesce times with like stacks
        - listitem [ref=e212]: Study stacks from largest to shortest time
    - heading "Stack Profile Method" [level=3] [ref=e213]
    - list [ref=e214]:
      - list [ref=e215]:
        - listitem [ref=e216]: Profile thread stack traces, on- and off-CPU
        - listitem [ref=e217]: Coalesce
        - listitem [ref=e218]: Study stacks bottom-up
    - heading "TSA Method" [level=3] [ref=e219]
    - list [ref=e220]:
      - list [ref=e221]:
        - listitem [ref=e222]: "For each thread of interest, measure time in operating system thread states. Eg:"
        - list [ref=e223]:
          - listitem [ref=e224]: Executing
          - listitem [ref=e225]: Runnable
          - listitem [ref=e226]: Swapping
          - listitem [ref=e227]: Sleeping
          - listitem [ref=e228]: Lock
          - listitem [ref=e229]: Idle
        - listitem [ref=e230]: Investigate states from most to least frequent, using appropriate tools
    - heading "Active Benchmarking Method" [level=3] [ref=e231]
    - list [ref=e232]:
      - list [ref=e233]:
        - listitem [ref=e234]: Configure the benchmark to run for a long duration
        - listitem [ref=e235]: While running, analyze performance using other tools, and determine limiting factors
    - heading "Method R" [level=3] [ref=e236]
    - list [ref=e237]:
      - list [ref=e238]:
        - listitem [ref=e239]: Select user actions that matter for the business workload
        - listitem [ref=e240]: Measure causes of response time for user actions
        - listitem [ref=e241]: Calculate best net-payoff optimization activity
        - list [ref=e242]:
          - listitem [ref=e243]: If sufficient gain, tune
          - listitem [ref=e244]: If insufficient gain, suspend tuning until something changes
        - listitem [ref=e245]: Goto 1
    - heading "Performance Evaluation Steps" [level=3] [ref=e246]
    - list [ref=e247]:
      - list [ref=e248]:
        - listitem [ref=e249]: State the goals of the study and define system boundaries
        - listitem [ref=e250]: List system services and possible outcomes
        - listitem [ref=e251]: Select performance metrics
        - listitem [ref=e252]: List system and workload parameters
        - listitem [ref=e253]: Select factors and their values
        - listitem [ref=e254]: Select the workload
        - listitem [ref=e255]: Design the experiments
        - listitem [ref=e256]: Analyze and interpret the data
        - listitem [ref=e257]: Present the results
        - listitem [ref=e258]: If necessary, start over
    - heading "Capacity Planning Process" [level=3] [ref=e259]
    - list [ref=e260]:
      - list [ref=e261]:
        - listitem [ref=e262]: Instrument the system
        - listitem [ref=e263]: Monitor system usage
        - listitem [ref=e264]: Characterize workload
        - listitem [ref=e265]: Predict performance under different alternatives
        - listitem [ref=e266]: Select the lowest cost, highest performance alternative
    - heading "Intel Hierarchical Top-Down Performance Characterization Methodology" [level=3] [ref=e267]
    - list [ref=e268]:
      - list [ref=e269]:
        - listitem [ref=e270]: Are UOPs issued?
        - list [ref=e271]:
          - listitem [ref=e272]: "If yes:"
          - list [ref=e273]:
            - listitem [ref=e274]: Are UOPs retired?
            - list [ref=e275]:
              - listitem [ref=e276]: "If yes: retiring (good)"
              - listitem [ref=e277]: "If no: investigate bad speculations"
          - listitem [ref=e278]: "If no:"
          - list [ref=e279]:
            - listitem [ref=e280]: Allocation stall?
            - list [ref=e281]:
              - listitem [ref=e282]: "If yes: investigate back-end stalls"
              - listitem [ref=e283]: "If no: investigate front-end stalls"
    - heading "Performance Mantras" [level=3] [ref=e284]
    - list [ref=e285]:
      - list [ref=e286]:
        - listitem [ref=e287]: Don't do it
        - listitem [ref=e288]: Do it, but don't do it again
        - listitem [ref=e289]: Do it less
        - listitem [ref=e290]: Do it later
        - listitem [ref=e291]: Do it when they're not looking
        - listitem [ref=e292]: Do it concurrently
        - listitem [ref=e293]: Do it cheaper
    - heading "Benchmarking Checklist" [level=3] [ref=e294]
    - list [ref=e295]:
      - list [ref=e296]:
        - listitem [ref=e297]: Why not double?
        - listitem [ref=e298]: Did it break limits?
        - listitem [ref=e299]: Did it error?
        - listitem [ref=e300]: Does it reproduce?
        - listitem [ref=e301]: Does it matter?
        - listitem [ref=e302]: Did it even happen?
    - heading "References" [level=2] [ref=e303]
    - list [ref=e304]:
      - listitem [ref=e305]: "Blame-Someone-Else Anti-Method and the USE Method were developed by me and first in print in [Gregg 13a]: Gregg, B., \"Thinking Methodically about Performance\", Communications of the ACM, Volume 56 Issue 2, Feb 2013. This article also included the Streetlight Anti-Method and the Problem Statement Method for the first time in print, also developed by me, but based on earlier work (the streetlight effect, https://en.wikipedia.org/wiki/Streetlight_effect, and initial performance checklists used by Sun Microsystems support)."
      - listitem [ref=e306]: "Random Change Anti-Method, Passive Benchmarking Anti-Method, Ad Hoc Checklist Method, Tools Method, TSA Method, and Active Benchmarking, were developed by me and first in print in [Gregg 13b]: Gregg, B., Systems Performance: Enterprise and the Cloud, Prentice Hall, Oct 2013."
      - listitem [ref=e307]: "My USENIX LISA 2012 talk: \"Performance Analysis Methodology\", first summarized and named many of these (before they were in print)."
      - listitem [ref=e308]: "Method R is from [Millsap 03]: Millsap, C., Holt, J., Optimizing Oracle Performance, O'Reilly, 2003."
      - listitem [ref=e309]: "Performance Evaluation Steps and Capacity Planning Process are from pages 26 and 124 of [Jain 91]: Jain, R., The Art of Computer Systems Performance Analysis: Techniques for Experimental Design, Measurement, Simulation, and Modeling, Wiley, 1991."
      - listitem [ref=e310]: Workload Characterization Method, and Drill-Down Analysis Method, were documented as specific methodologies in [Gregg 13a] and [Gregg 13b], but the general process has been known in IT for many years. You could glean it from [Jain 91], at least. I don't yet have an earlier reference.
      - listitem [ref=e311]: Intel Hierarchical Top-Down Performance Characterization Methodology was developed by Ahmad Yasin at Intel and documented in B.3.2 of the Intel 64 and IA-32 Architectures Optimization Reference Manual, 248966-030, Sep 2014.
      - listitem [ref=e312]: OODA Loop is from Joyd Boyd of the US Air Force, and popularized in technology by Roy Rapoport of Netflix.
      - listitem [ref=e313]: Performance Mantas is from Craig Hanson and Pat Crain.
      - listitem [ref=e314]:
        - text: Benchmarking Checklist was developed by
        - link "me" [ref=e315] [cursor=pointer]:
          - /url: http://www.brendangregg.com/blog/2018-06-30/benchmarking-checklist.html
        - text: .
      - listitem [ref=e316]: RED Method is from Tom Wilkie.
  - separator [ref=e317]
  - text: "Last Updated: 23-Jan-2025"