// Bashrc builder — composes the managed-block body from the fragment modules.
//
// Each fragment is a self-contained bash snippet exported as a string. The
// builder concatenates them with consistent spacing. This is the ONLY place
// in the codebase that knows the order — no fragment imports another.
//
// To add a new fragment: write src/bashrc/<name>.ts exporting a string,
// import it here, push to FRAGMENTS in the right place. The bashrc module
// (src/modules/bashrc.ts) calls buildBashrcBody() and writes the result.

import { COMPLETIONS_BLOCK } from "./completions.ts";
import { EXPLAIN_FN_BLOCK } from "./explain-fn.ts";
import { PRODUCTIVITY_ALIASES_BLOCK } from "./productivity-aliases.ts";
import { repoAliasesBlock } from "./repo-aliases.ts";
import { SAFETY_BLOCK } from "./safety.ts";
import { TOOL_INIT_BLOCK } from "./tool-init.ts";

export interface BashrcBuilderInput {
  readonly repoDir: string;
}

export function buildBashrcBody(input: BashrcBuilderInput): string {
  const header = `# Generated by @domains/bootstrap. Re-run \`pnpm bootstrap install\` to regenerate.
# To temporarily disable, comment out this whole block (between the markers).
# To remove permanently, run \`pnpm bootstrap install --module=bashrc-remove\`.`;

  const fragments: readonly string[] = [
    header,
    TOOL_INIT_BLOCK,
    COMPLETIONS_BLOCK,
    PRODUCTIVITY_ALIASES_BLOCK,
    repoAliasesBlock(input.repoDir),
    EXPLAIN_FN_BLOCK,
    SAFETY_BLOCK,
  ];

  return fragments.map((f) => f.trim()).join("\n\n");
}
