import json
from datetime import datetime, timezone
from pathlib import Path

import duckdb

from ingest.models import Document, Source
from ingest.paths import (
    DB_DIR,
    DB_PATH,
    DOMAINS_DIR,
    DOMAIN_SCHEMAS,
    SHARED_QUERIES,
    SHARED_SCHEMA_SQL,
    STAGING_DIR,
    domain_schema_extension,
)

# Base tables every domain gets from schema.sql; the only ones unioned into the meta.* views.
# Per-domain schema-extension tables stay domain-local (queried directly, not cross-domain).
# `claims` was promoted from per-domain to base so the gold layer is uniform and meta.all_claims exists.
BASE_TABLES: tuple[str, ...] = (
    "sources",
    "documents",
    "concepts",
    "commands",
    "config_keys",
    "failure_modes",
    "relationships",
    "claims",
    "forecast_log",
    "claim_evidence",
    "primary_studies",
    "claim_history",
)


def open_db(read_only: bool = False) -> duckdb.DuckDBPyConnection:
    DB_DIR.mkdir(parents=True, exist_ok=True)
    return duckdb.connect(str(DB_PATH), read_only=read_only)


def _render_meta_views(domains: tuple[str, ...]) -> str:
    """Generate the meta.all_* cross-domain views from the live domain list.

    Regenerated by init_db so adding a domain folder wires it into `meta.*` with no
    hand-editing. Only the shared base tables are unioned (every domain has them);
    per-domain schema-extension tables stay domain-local.
    """
    lines = [
        "-- AUTO-GENERATED by `ingest init-db` from the domain folders under domains/.",
        "-- Do not hand-edit; re-run init-db after adding or removing a domain.",
        "",
        "CREATE SCHEMA IF NOT EXISTS meta;",
        "",
    ]
    for table in BASE_TABLES:
        selects = [f"  SELECT '{d}' AS domain, * FROM {d}.{table}" for d in domains]
        body = " UNION ALL BY NAME\n".join(selects)
        lines.append(f"CREATE OR REPLACE VIEW meta.all_{table} AS\n{body};\n")
    return "\n".join(lines)


def _render_fts_index(domains: tuple[str, ...]) -> str:
    """Generate the BM25 FTS build script for every domain's documents table."""
    lines = [
        "-- AUTO-GENERATED by `ingest init-db`. Build BM25 FTS indexes per domain.",
        "-- Run after a bulk ingest:  duckdb _db/knowledge.duckdb < this-file",
        "",
        "INSTALL fts;",
        "LOAD fts;",
        "",
    ]
    for d in domains:
        lines.append(
            f"PRAGMA create_fts_index('{d}.documents', 'source_id', 'content_md', "
            "stemmer='porter', stopwords='english', overwrite=1);"
        )
    return "\n".join(lines) + "\n"


def init_db() -> None:
    """Create all domain schemas + tables in the DuckDB file. Idempotent.

    For each auto-discovered domain folder: apply the shared base schema, then an optional
    per-domain `schema.<domain>.sql` extension. Then regenerate + execute the cross-domain
    meta views and regenerate the FTS build script — both derived from the live domain list,
    so a new domain needs no manual wiring.
    """
    template = SHARED_SCHEMA_SQL.read_text(encoding="utf-8")
    domains = DOMAIN_SCHEMAS
    con = open_db(read_only=False)
    try:
        for schema in domains:
            con.execute(template.replace("{{schema}}", schema))
            ext = domain_schema_extension(schema)
            if ext is not None:
                con.execute(ext.read_text(encoding="utf-8").replace("{{schema}}", schema))
        if domains:
            meta_sql = _render_meta_views(domains)
            (SHARED_QUERIES / "cross_domain.sql").write_text(meta_sql, encoding="utf-8")
            con.execute(meta_sql)
            (SHARED_QUERIES / "fts_index.sql").write_text(
                _render_fts_index(domains), encoding="utf-8"
            )
    finally:
        con.close()


# ---------------------------------------------------------------- staging

def _staging_paths(domain: str) -> tuple[Path, Path]:
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    return (
        STAGING_DIR / f"{domain}.sources.jsonl",
        STAGING_DIR / f"{domain}.documents.jsonl",
    )


def clear_staging(domain: str) -> None:
    src_p, doc_p = _staging_paths(domain)
    src_p.write_text("", encoding="utf-8")
    doc_p.write_text("", encoding="utf-8")


def stage_source(src: Source) -> None:
    src_p, _ = _staging_paths(src.domain)
    row = {
        "id": src.id,
        "url": src.url,
        "title": src.title,
        "subdomain": src.subdomain,
        "tier": src.tier,
        "license_note": src.license_note,
        "fetched_at": (src.fetched_at or datetime.now(timezone.utc)).isoformat(),
        "content_hash": src.content_hash,
        "parser": src.parser,
        "notes": src.notes,
        "evidence_class": src.evidence_class,
        "primary_kind": src.primary_kind,
    }
    with src_p.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")


def stage_document(doc: Document, domain: str) -> None:
    _, doc_p = _staging_paths(domain)
    row = {
        "source_id": doc.source_id,
        "section_path": doc.section_path,
        "content_md": doc.content_md,
    }
    with doc_p.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")


# ------------------------------------------------------------------- load

def load_staged(con: duckdb.DuckDBPyConnection, domain: str) -> tuple[int, int]:
    """Read staged JSONL for `domain` and INSERT OR REPLACE into <domain>.sources / .documents.

    Returns (sources_loaded, documents_loaded). Caller owns the connection (which holds the DB
    write lock); this function does no commit/rollback management.
    """
    src_p, doc_p = _staging_paths(domain)
    s_n = _load_jsonl(con, src_p, f"{domain}.sources")
    d_n = _load_jsonl(con, doc_p, f"{domain}.documents")
    return s_n, d_n


def load_extract(
    con: duckdb.DuckDBPyConnection, domain: str, leaf: str | None = None
) -> dict[str, int]:
    """Upsert committed extension-table rows from domains/<domain>/[<leaf>/]extract/*.json.

    Convention: each JSON file is either {table_name: [rows], ...} (top-level keys name target
    tables) or a bare [rows] list (table = file stem). Only keys matching an EXISTING table in
    the domain schema are loaded — non-table keys (e.g. a figure's name/caption/sql) are skipped,
    so mixed extract/ dirs are safe. Each table loads via the same _load_jsonl ON CONFLICT path as
    sources/documents. Returns {table: rows_loaded}; a per-table failure is reported, not fatal.
    """
    base = DOMAINS_DIR / domain
    files = (
        sorted((base / leaf / "extract").glob("*.json"))
        if leaf
        else sorted(base.glob("*/extract/*.json"))
    )
    existing = {
        r[0]
        for r in con.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = ?", [domain]
        ).fetchall()
    }
    counts: dict[str, int] = {}
    STAGING_DIR.mkdir(parents=True, exist_ok=True)
    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            continue
        groups = data if isinstance(data, dict) else {path.stem: data}
        for table, rows in groups.items():
            if table not in existing or not isinstance(rows, list) or not rows:
                continue
            tmp = STAGING_DIR / f"{domain}.{table}.extract.jsonl"
            with tmp.open("w", encoding="utf-8") as f:
                for r in rows:
                    f.write(json.dumps(r, default=str) + "\n")
            try:
                n = _load_jsonl(con, tmp, f"{domain}.{table}")
                counts[table] = counts.get(table, 0) + n
            except Exception as e:  # noqa: BLE001
                counts[f"{table} (FAILED: {type(e).__name__})"] = -1
    return counts


def _pk_columns(con: duckdb.DuckDBPyConnection, schema: str, table: str) -> list[str]:
    row = con.execute(
        "SELECT constraint_column_names FROM duckdb_constraints() "
        "WHERE schema_name = ? AND table_name = ? AND constraint_type = 'PRIMARY KEY'",
        [schema, table],
    ).fetchone()
    return list(row[0]) if row else []


def _table_columns(con: duckdb.DuckDBPyConnection, schema: str, table: str) -> list[str]:
    return [
        r[0]
        for r in con.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position",
            [schema, table],
        ).fetchall()
    ]


def _load_jsonl(con: duckdb.DuckDBPyConnection, path: Path, qualified: str) -> int:
    """Upsert a staged JSONL into `qualified` (schema.table) via in-place ON CONFLICT DO UPDATE.

    Uses UPDATE (not INSERT OR REPLACE, which is delete+reinsert) so re-loads don't violate the
    documents.source_id -> sources.id foreign key when a referenced source row already exists.
    """
    if not path.is_file() or path.stat().st_size == 0:
        return 0
    posix = path.as_posix()
    schema, table = qualified.split(".", 1)
    pk = _pk_columns(con, schema, table)
    non_pk = [c for c in _table_columns(con, schema, table) if c not in pk]
    src = f"read_json('{posix}', format='newline_delimited')"
    if pk and non_pk:
        conflict = ", ".join(f'"{c}"' for c in pk)
        set_clause = ", ".join(f'"{c}" = excluded."{c}"' for c in non_pk)
        con.execute(
            f"INSERT INTO {qualified} BY NAME SELECT * FROM {src} "
            f"ON CONFLICT ({conflict}) DO UPDATE SET {set_clause}"
        )
    elif pk:
        con.execute(f"INSERT INTO {qualified} BY NAME SELECT * FROM {src} ON CONFLICT DO NOTHING")
    else:
        con.execute(f"INSERT INTO {qualified} BY NAME SELECT * FROM {src}")
    return con.execute(f"SELECT count(*) FROM {src}").fetchone()[0]


# ------------------------------------------------------ legacy direct upserts
# Retained for ad-hoc one-source flows; the standard path is stage_* + load_staged.

def upsert_source(con: duckdb.DuckDBPyConnection, src: Source) -> None:
    con.execute(
        f"""
        INSERT OR REPLACE INTO {src.domain}.sources
            (id, url, title, subdomain, tier, license_note, fetched_at, content_hash, parser, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            src.id,
            src.url,
            src.title,
            src.subdomain,
            src.tier,
            src.license_note,
            src.fetched_at or datetime.now(timezone.utc),
            src.content_hash,
            src.parser,
            src.notes,
        ],
    )


def upsert_document(con: duckdb.DuckDBPyConnection, doc: Document, domain: str) -> None:
    con.execute(
        f"""
        INSERT OR REPLACE INTO {domain}.documents (source_id, section_path, content_md)
        VALUES (?, ?, ?)
        """,
        [doc.source_id, doc.section_path, doc.content_md],
    )
