"""Layer 7 — render. Project the strategy domain's shared `render_blocks` into a non-divergent family of
human-readable artifacts (investor deck, strategy memo, per-competitor battlecards, board update).

Each artifact is a PURE PROJECTION over `strategy.artifact_blocks` ⋈ `strategy.render_blocks`: a metric
shared across artifacts renders from the SAME block, so the same number is byte-identical everywhere
(structural non-divergence — proven, not asserted). Verdict glyphs make the evidence grade self-auditing,
so a proxy-only wedge metric can never be silently dressed up as measured. The roadmap, wedge-evidence,
and risk appendices are projected the same way (recommendations / wedge_reeval / red_team_findings).

`ingest render [--out <dir>]` writes one .md per artifact under domains/strategy/render/ (committed,
regenerable). Read-only on every other domain.
"""

import duckdb

from ingest.paths import DOMAINS_DIR

# self-auditing badges — the evidence grade travels with every rendered value
GLYPH = {
    "modeled": "📊 modeled",
    "proxy": "◑ supported-by-proxy",
    "contested": "⚠ contested",
    "speculative": "◌ speculative",
    "supported": "✓ supported",
}
CEIL_GLYPH = {
    "supported-by-proxy": "◑ supported-by-proxy",
    "contested": "⚠ contested",
    "weak-proxy": "◔ weak-proxy",
    "corpus-refuted-only": "✗ corpus-refuted-only",
}

TITLES = {
    "investor-deck": "MetroGraph — Investor Deck",
    "strategy-memo": "MetroGraph — Strategy Memo",
    "board-update": "MetroGraph — Board Update",
}


def _title(artifact: str) -> str:
    if artifact.startswith("battlecard:"):
        return f"MetroGraph — Battlecard vs {artifact.split(':', 1)[1].title()}"
    return TITLES.get(artifact, f"MetroGraph — {artifact}")


def _blocks_for(con, artifact: str) -> list[tuple]:
    return con.execute(
        """
        SELECT rb.block_kind, rb.label, rb.value_text, rb.verdict_glyph,
               rb.resolves_claim_id, rb.resolves_source_id
        FROM strategy.artifact_blocks ab
        JOIN strategy.render_blocks rb ON rb.id = ab.block_id
        WHERE ab.artifact = ?
        ORDER BY ab.ordinal
        """,
        [artifact],
    ).fetchall()


def _roadmap(con) -> list[tuple]:
    return con.execute(
        """SELECT kind, statement, priority_score, effort, is_experiment, tradeoffs
           FROM strategy.recommendations ORDER BY priority_score DESC"""
    ).fetchall()


def _wedge(con) -> list[tuple]:
    return con.execute(
        """SELECT market_claim_id, market_verdict, cross_domain_ceiling, needed_experiment
           FROM strategy.wedge_reeval ORDER BY cross_domain_ceiling, market_claim_id"""
    ).fetchall()


def _risks(con) -> list[tuple]:
    return con.execute(
        """SELECT kind, statement, severity, fired, mitigation
           FROM strategy.red_team_findings ORDER BY fired DESC, severity"""
    ).fetchall()


def _render_one(con, artifact: str) -> str:
    L: list[str] = [f"# {_title(artifact)}", ""]
    L.append("> Auto-generated by `ingest render` — a pure projection of `strategy.render_blocks`. "
             "Every figure carries its evidence glyph and resolves to one `claim_id` / `source_id`; "
             "the same block renders identically in every artifact (structural non-divergence). "
             "Do not hand-edit — re-run `ingest render`.")
    L.append("")

    metrics = [b for b in _blocks_for(con, artifact) if b[0] == "metric"]
    others = [b for b in _blocks_for(con, artifact) if b[0] != "metric"]

    if metrics:
        L += ["## Headline metrics", "", "| Metric | Value | Evidence | Resolves to |", "| --- | --- | --- | --- |"]
        for _, label, value, glyph, claim, src in metrics:
            L.append(f"| {label} | **{value}** | {GLYPH.get(glyph, glyph)} | `{claim or '—'}` |")
        L.append("")

    for kind, label, value, glyph, claim, src in others:
        head = {"claim": "Lead thesis", "risk": "Risk", "recommendation": "Recommendation"}.get(kind, kind.title())
        L += [f"## {head}: {label}", "", f"- {value}  — {GLYPH.get(glyph, glyph)}",
              f"- _cites_ `{claim or '—'}` / `{src or '—'}`", ""]

    # battlecards stay tight; full appendices only on deck/memo/board
    if not artifact.startswith("battlecard:"):
        rm = _roadmap(con)
        if rm:
            L += ["## Prioritized roadmap", "",
                  "_Priority is derived (cited-claim confidence × impact ÷ effort) — it recomputes when "
                  "facts change. Experiments are the needed-but-missing validation studies, emitted as "
                  "first-class roadmap items._", "",
                  "| Priority | Kind | Effort | Action |", "| --- | --- | --- | --- |"]
            for kind, stmt, prio, effort, is_exp, _tr in rm:
                tag = "🔬 experiment" if is_exp else kind
                L.append(f"| {prio:.3f} | {tag} | {effort} | {stmt} |")
            L.append("")

        wd = _wedge(con)
        if wd:
            L += ["## Wedge evidence status (honest ceilings)", "",
                  "_The differentiating claims, re-graded against cross-domain evidence. The ceiling is "
                  "**supported-by-proxy** — never experimental — because no MetroGraph behavioral study "
                  "exists yet. Each names the study that would lift it._", "",
                  "| Wedge claim | Corpus verdict | Cross-domain ceiling | Needed study |",
                  "| --- | --- | --- | --- |"]
            for claim, verdict, ceiling, need in wd:
                short = claim.replace("market.claim.", "")
                L.append(f"| {short} | {verdict} | {CEIL_GLYPH.get(ceiling, ceiling)} | {need[:90]}… |")
            L.append("")

        rk = _risks(con)
        if rk:
            L += ["## Red-team (standing bear case)", ""]
            for kind, stmt, sev, fired, mit in rk:
                state = "🔴 **FIRED**" if fired else "⚪ watching"
                L += [f"- {state} · _{sev}_ · **{kind}** — {stmt}", f"  - _Mitigation:_ {mit}"]
            L.append("")

    L.append("---")
    L.append("_All claims trace to the cross-domain corpus; proxy/contested grades are surfaced, not "
             "hidden. Generated from the committed snapshot — regenerate with `ingest render`._")
    return "\n".join(L) + "\n"


def render(con: duckdb.DuckDBPyConnection, out_dir=None) -> list[str]:
    """Render every artifact named in strategy.artifact_blocks to <out_dir>/<artifact>.md."""
    out_dir = out_dir or (DOMAINS_DIR / "strategy" / "render")
    out_dir.mkdir(parents=True, exist_ok=True)
    artifacts = [r[0] for r in con.execute(
        "SELECT DISTINCT artifact FROM strategy.artifact_blocks ORDER BY artifact").fetchall()]
    written: list[str] = []
    for a in artifacts:
        fname = a.replace(":", "-") + ".md"
        path = out_dir / fname
        path.write_text(_render_one(con, a), encoding="utf-8")
        written.append(str(path.relative_to(DOMAINS_DIR.parent)))
    return written
